

zeebe.client.cloud.clusterId=3355bd58-8969-4de5-95d8-edad3787bab1
zeebe.client.cloud.clientId=~0liGU22bOjn8etwSq0-h9_cMiV1Bbfb
zeebe.client.cloud.clientSecret=TRO3Z.lBrm2BtAaKnuBx55qpKP_wFTcf0vDL2IDop~5q.QGx8Bq-OD4sWJ~fOTP2
zeebe.client.cloud.region=lhr-1

database.postgresql.dburl=jdbc:postgresql://195.150.230.208:5432/2023_kindra_patryk
database.postgresql.dbuser=2023_kindra_patryk
database.postgresql.dbpassword=36375


# Konfiguracja bazy danych
spring.datasource.url=${database.postgresql.dburl}
spring.datasource.username=${database.postgresql.dbuser}
spring.datasource.password=${database.postgresql.dbpassword}
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=cinema



server.port=8080

spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=

mail.anstar.edu.pl.mailsmtphost=
mail.anstar.edu.pl.mailuser=
mail.anstar.edu.pl.mailpassword=
mail.anstar.edu.pl.mailsendermail=
mail.anstar.edu.pl.mailsendername=

radon.nauka.gov.pl.url=https://radon.nauka.gov.pl/opendata/polon/courses?resultNumbers=100&leadingInstitutionUuid=df584ad3-5474-4618-812a-2e10b03b48c0
radon.nauka.gov.pl.apiKey=

